global using Entity;
global using Entity.CMSMod;
global using Entity.ResourceMod;
global using Entity.SystemMod;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Perigon.AspNetCore.Abstraction;
global using Perigon.AspNetCore.Options;
global using System.Linq.Expressions;
